### PR TITLE
PostgreSQL local setup 

### PR DESCRIPTION
**Pull request by johnagl**
Summary:
- Integrated PostgreSQL database into Express server
- Added instructions to README for local setup of PostgreSQL (since we don't have Docker yet)

If you have Postgres (@danielchen-pyc)  installed currently try to run the local setup. 

Issues:
#9

### CODE REVIEW

**Review by resurl — APPROVED** [review]
works on my end!

**Comment by johnagl** [comment]
> works on my end!

@resurreccionl Did you have Postgres from before? Or did you follow the README instructions to install it? :)

**Comment by resurl** [comment]
@johnagl I followed the README!

**Comment by johnagl** [comment]
> @johnagl I followed the README!

Nice!! Good to know it's understandable :D

**Pull request merged**
