### PR TITLE
Redux Set Up

### PR DESCRIPTION
**Pull request by aldy97**
# Changes
- Set up global state management using Redux and immutable.js
- Added one sample useage of mapStateToProps and mapDispatchToProps
- Set up combineReducers using imutable.js
- Set up for Redux Devtools (a chrome plugin for tracking global state changes) 

## Motivation and Context
- Some data needs to be stored globaly in order to be accessed by more than one component when receiving props is very difficult or even impossible.
- For example, the user has selected all courses he/she wants to take. After next button is clicked, a new slide (React component) is rendered. We might still need to present courses selected from the previous slide (which is also a component) even though it has been dismounted from the DOM tree.

## How Has This Been Tested?
- In page1, the number is 0 intially. Clicking on "Add One' makes it incremented by one. Redux DevTools is able to track the change.

# Related Issues
- Redux is only able to record global data within the same Route. So, when we need to stay on the same page in order to maintain the data stored.

### CODE REVIEW

**Comment by johnagl** [comment]
Really good start ! I like how there's an example that everyone can look to if they've never seen redux. A few comments:

1) We should structure our folders either by **domain** or by **nature**. 

- Personally I like the idea of structuring folders in client by domain.  Redux docs (https://redux.js.org/faq/code-structure) references this article https://marmelab.com/blog/2015/12/17/react-directory-structure.html. For example, we might have a domain **"Counter"** that adds / decrements a count whenever clicking a button (the example in the code right now). Inside the Counter folder we can have the relevant actions, reducers etc (eg. counterreducer, counteractions). See the article for more examples. 

- A common way to structure react redux applications is to group things by **"nature"** (ie: having folders for action, component, container, reducer). The problem with this is when we need to add code about a new domain/feature, including actions, components, and a reducer, we're having to add files in **multiple directories**. <- This isn't great and  I'd rather not structure things this way but it is common so I wouldn't mind doing it this way. @ubclaunchpad/life-at-ubc  please comment if you have experience with Redux

2) We're using TypeScript so every file should have a **.tsx** or **.ts** suffix and not .js.

**Comment by aldy97** [comment]
@johnagl I didnot know about folder structure involving Redux too much! Thanks for sharing! That's really helpful! For now, is the current structure more like by nature based on my knowledge from reading the article? So should we make adjustments towards this direction? And yeah, I will change all js files to tsx files and minimize the usage of any in them.

**Comment by johnagl** [comment]
> @johnagl I didnot know about folder structure involving Redux too much! Thanks for sharing! That's really helpful! For now, is the current structure more like by nature based on my knowledge from reading the article? So should we make adjustments towards this direction? And yeah, I will change all js files to tsx files and minimize the usage of any in them.

I guess it's kind of like nature - but not really tbh because there are no folders for reducers, actions etc.

**Comment by johnagl** [comment]
We should structure our folders by either domain or nature. So you'll have to make a few changes depending on which one you decide to choose.

**Comment by aldy97** [comment]
I am currently learning how to use Redux with TS (I only used it in JS previously). I think this video is a good resource: https://www.youtube.com/watch?v=dZZxegovK9Q&list=WL&index=41&t=213s&ab_channel=CoryMcAboy If anyone is interested in learning Redux, please check this out!

**Pull request closed without merging**
