### PR TITLE
Code changes in server should be reflected when running Docker

### PR DESCRIPTION
**Pull request by johnagl**
# Changes
- Add -L flag to npm run dev script in package.json because windows is bad :) 
- Minor changes to Dockerfile and compose file to facilitate restarting on code changes when running backend in docker

## Motivation and Context
Previously, making code changes was not reflected in docker container. Restart of docker container required.

## How Has This Been Tested?
- Ran server in docker
- Made a code change (eg. add a console.log in server/src/index.ts)
- observe change in terminal

## Screenshots (if appropriate):

# Related Issues
- Closes issue #21 

# Checklist

### CODE REVIEW

**Comment by johnagl** [comment]
I think I'm supposed to also add node_modules to volumes in server.

**Comment by resurl** [comment]
> I think I'm supposed to also add node_modules to volumes in server.

@johnagl i'm not 100% sure but i think it might not be necessary? i tried setting up pino (`npm install pino` and used it in `index.ts`) while the docker container was up and it did track the changes 🥳

**Review by resurl — APPROVED** [review]

**Comment by johnagl** [comment]
@ubclaunchpad/life-at-ubc If a mac user could test this, would be greatly appreciated !

**Review by yehee — APPROVED** [review]
Works on Mac!

**Comment by yehee** [comment]
> I think I'm supposed to also add node_modules to volumes in server.

Not sure if this is related, but I saw an example where they explicitly exclude `node_modules` so that it doesn’t get sync-ed to the container: https://codewithhugo.com/node-postgres-express-docker-compose/

**Comment by johnagl** [comment]
> > I think I'm supposed to also add node_modules to volumes in server.
> 
> Not sure if this is related, but I saw an example where they explicitly exclude `node_modules` so that it doesn’t get sync-ed to the container: https://codewithhugo.com/node-postgres-express-docker-compose/

Oh that makes sense...From reading that my understanding is we dont wan't node_modules because docker has to compare host node_modules to container node_modules and that takes up too many resources for a single code update since node_modules is so massive. Also that article would have been useful at the very start of our project LOL, very relevant to our stack.

**Pull request merged**
