### PR TITLE
Set up tsc linter and fixed files

### LINKED ISSUE #6: Add Basic Linting
Add common TypeScript linting rules using [ESLint](https://eslint.org/) .

### PR DESCRIPTION
**Pull request by jacksonyuanjx**
# Description
* set up eslint in `/client` and `/server` directories
* set up `lint` and `fix` scripts in `package.json`

# Note
* lmk if anyone has any additional suggestions for the lint rules and I can add/remove them :)

### CODE REVIEW

**Comment by johnagl** [comment]
I'm getting a bunch of errors in the terminal - which I think has to do with the eslintrc.js file not matching up correctly with the tsconfig.json - have to look into this more later. 


Particularly the one below. I changed the config path because it was looking for tsconfig.json in the root , not in server file, so there was a different error initially.

`Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: server\.eslintrc.js.
The file must be included in at least one of the projects provided.`

**Comment by jacksonyuanjx** [comment]
> I'm getting a bunch of errors in the terminal - which I think has to do with the eslintrc.js file not matching up correctly with the tsconfig.json - have to look into this more later.
> 
> Particularly the one below. I changed the config path because it was looking for tsconfig.json in the root , not in server file, so there was a different error initially.
> 
> `Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser. The file does not match your project config: server\.eslintrc.js. The file must be included in at least one of the projects provided.`

The last 2 commits should fix it but lmk if it still doesn't work for anyone!

**Comment by johnagl** [comment]
Works now only after running `npm run lint`. But linting errors aren't automatically underlined in VSCode .  Nice job! @jacksonyuanjx. I believe we need a .vscode file in the root, with settings.json - we can deal with this later.

**Review by johnagl — DISMISSED** [review]

**Comment by resurl** [comment]
sorry, i've never used a linter before so maybe i'm doing something wrong? `npm run lint` completes fine (nothing seems to happen though?) on both `/client` and `/server`, but I ran `npm start` in `/client` (running it in the server dir works fine) and I got some errors that im guessing shouldn't happen lol

`npm install`
```bash
// some dependency warnings
added 1685 packages from 809 contributors and audited 1691 packages in 367.284s

80 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
```

`npm start`
```
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:


Don't try to install it manually: your package manager does it automatically.
However, a different version of eslint was detected higher up in the tree:

  C:\Users\Leanna\Documents\code\life-at-ubc\client\node_modules\eslint (version: 7.11.0)

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if C:\Users\Leanna\Documents\code\life-at-ubc\client\node_modules\eslint is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls eslint in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed eslint.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!

npm ERR! errno 1
npm ERR! client@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the client@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Leanna\AppData\Roaming\npm-cache\_logs\2020-10-22T23_24_18_947Z-debug.log
PS C:\Users\Leanna\Documents\code\life-at-ubc\client> npm ls eslint
client@0.1.0 C:\Users\Leanna\Documents\code\life-at-ubc\client
+-- eslint@7.11.0
`-- react-scripts@3.4.3
  `-- UNMET PEER DEPENDENCY eslint@6.8.0

npm ERR! peer dep missing: eslint@^5.0.0 || ^6.0.0, required by @typescript-eslint/eslint-plugin@2.34.0
npm ERR! peer dep missing: eslint@^5.0.0 || ^6.0.0, required by @typescript-eslint/parser@2.34.0
npm ERR! peer dep missing: eslint@6.x, required by eslint-config-react-app@5.2.1
npm ERR! peer dep missing: eslint@^5.0.0 || ^6.0.0, required by eslint-loader@3.0.3
npm ERR! peer dep missing: eslint@2.x - 6.x, required by eslint-plugin-import@2.20.1
npm ERR! peer dep missing: eslint@^3 || ^4 || ^5 || ^6, required by eslint-plugin-jsx-a11y@6.2.3
npm ERR! peer dep missing: eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0, required by eslint-plugin-react-hooks@1.7.0
```
i checked my `node_modules` and confirmed eslint@7.11.0 is there.

**Comment by johnagl** [comment]
> sorry, i've never used a linter before so maybe i'm doing something wrong? `npm run lint` completes fine (nothing seems to happen though?) on both `/client` and `/server`, but I ran `npm start` in `/client` (running it in the server dir works fine) and I got some errors that im guessing shouldn't happen lol
> 
> `npm install`
> 
> ```shell
> // some dependency warnings
> added 1685 packages from 809 contributors and audited 1691 packages in 367.284s
> 
> 80 packages are looking for funding
>   run `npm fund` for details
> 
> found 1 high severity vulnerability
> ```
> 
> `npm start`
> 
> ```
> There might be a problem with the project dependency tree.
> It is likely not a bug in Create React App, but something you need to fix locally.
> 
> The react-scripts package provided by Create React App requires a dependency:
> 
> 
> Don't try to install it manually: your package manager does it automatically.
> However, a different version of eslint was detected higher up in the tree:
> 
>   C:\Users\Leanna\Documents\code\life-at-ubc\client\node_modules\eslint (version: 7.11.0)
> 
> Manually installing incompatible versions is known to cause hard-to-debug issues.
> 
> If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
> That will permanently disable this message but you might encounter other issues.
> 
> To fix the dependency tree, try following the steps below in the exact order:
> 
>   4. Run npm install or yarn, depending on the package manager you use.
> 
> In most cases, this should be enough to fix the problem.
> If this has not helped, there are a few other things you can try:
> 
>   5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
>      This may help because npm has known issues with package hoisting which may get resolved in future versions.
> 
>   6. Check if C:\Users\Leanna\Documents\code\life-at-ubc\client\node_modules\eslint is outside your project directory.
>      For example, you might have accidentally installed something in your home folder.
> 
>   7. Try running npm ls eslint in your project folder.
>      This will tell you which other package (apart from the expected react-scripts) installed eslint.
> 
> If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
> That would permanently disable this preflight check in case you want to proceed anyway.
> 
> P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!
> 
> npm ERR! errno 1
> npm ERR! client@0.1.0 start: `react-scripts start`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the client@0.1.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Leanna\AppData\Roaming\npm-cache\_logs\2020-10-22T23_24_18_947Z-debug.log
> PS C:\Users\Leanna\Documents\code\life-at-ubc\client> npm ls eslint
> client@0.1.0 C:\Users\Leanna\Documents\code\life-at-ubc\client
> +-- eslint@7.11.0
> `-- react-scripts@3.4.3
>   `-- UNMET PEER DEPENDENCY eslint@6.8.0
> 
> npm ERR! peer dep missing: eslint@^5.0.0 || ^6.0.0, required by @typescript-eslint/eslint-plugin@2.34.0
> npm ERR! peer dep missing: eslint@^5.0.0 || ^6.0.0, required by @typescript-eslint/parser@2.34.0
> npm ERR! peer dep missing: eslint@6.x, required by eslint-config-react-app@5.2.1
> npm ERR! peer dep missing: eslint@^5.0.0 || ^6.0.0, required by eslint-loader@3.0.3
> npm ERR! peer dep missing: eslint@2.x - 6.x, required by eslint-plugin-import@2.20.1
> npm ERR! peer dep missing: eslint@^3 || ^4 || ^5 || ^6, required by eslint-plugin-jsx-a11y@6.2.3
> npm ERR! peer dep missing: eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0, required by eslint-plugin-react-hooks@1.7.0
> ```
> 
> i checked my `node_modules` and confirmed eslint@7.11.0 is there.



> sorry, i've never used a linter before so maybe i'm doing something wrong? `npm run lint` completes fine (nothing seems to happen though?) on both `/client` and `/server`, but I ran `npm start` in `/client` (running it in the server dir works fine) and I got some errors that im guessing shouldn't happen lol
> 
> `npm install`
> 
> ```shell
> // some dependency warnings
> added 1685 packages from 809 contributors and audited 1691 packages in 367.284s
> 
> 80 packages are looking for funding
>   run `npm fund` for details
> 
> found 1 high severity vulnerability
> ```
> 
> `npm start`
> 
> ```
> There might be a problem with the project dependency tree.
> It is likely not a bug in Create React App, but something you need to fix locally.
> 
> The react-scripts package provided by Create React App requires a dependency:
> 
> 
> Don't try to install it manually: your package manager does it automatically.
> However, a different version of eslint was detected higher up in the tree:
> 
>   C:\Users\Leanna\Documents\code\life-at-ubc\client\node_modules\eslint (version: 7.11.0)
> 
> Manually installing incompatible versions is known to cause hard-to-debug issues.
> 
> If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
> That will permanently disable this message but you might encounter other issues.
> 
> To fix the dependency tree, try following the steps below in the exact order:
> 
>   4. Run npm install or yarn, depending on the package manager you use.
> 
> In most cases, this should be enough to fix the problem.
> If this has not helped, there are a few other things you can try:
> 
>   5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
>      This may help because npm has known issues with package hoisting which may get resolved in future versions.
> 
>   6. Check if C:\Users\Leanna\Documents\code\life-at-ubc\client\node_modules\eslint is outside your project directory.
>      For example, you might have accidentally installed something in your home folder.
> 
>   7. Try running npm ls eslint in your project folder.
>      This will tell you which other package (apart from the expected react-scripts) installed eslint.
> 
> If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
> That would permanently disable this preflight check in case you want to proceed anyway.
> 
> P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!
> 
> npm ERR! errno 1
> npm ERR! client@0.1.0 start: `react-scripts start`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the client@0.1.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Leanna\AppData\Roaming\npm-cache\_logs\2020-10-22T23_24_18_947Z-debug.log
> PS C:\Users\Leanna\Documents\code\life-at-ubc\client> npm ls eslint
> client@0.1.0 C:\Users\Leanna\Documents\code\life-at-ubc\client
> +-- eslint@7.11.0
> `-- react-scripts@3.4.3
>   `-- UNMET PEER DEPENDENCY eslint@6.8.0
> 
> npm ERR! peer dep missing: eslint@^5.0.0 || ^6.0.0, required by @typescript-eslint/eslint-plugin@2.34.0
> npm ERR! peer dep missing: eslint@^5.0.0 || ^6.0.0, required by @typescript-eslint/parser@2.34.0
> npm ERR! peer dep missing: eslint@6.x, required by eslint-config-react-app@5.2.1
> npm ERR! peer dep missing: eslint@^5.0.0 || ^6.0.0, required by eslint-loader@3.0.3
> npm ERR! peer dep missing: eslint@2.x - 6.x, required by eslint-plugin-import@2.20.1
> npm ERR! peer dep missing: eslint@^3 || ^4 || ^5 || ^6, required by eslint-plugin-jsx-a11y@6.2.3
> npm ERR! peer dep missing: eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0, required by eslint-plugin-react-hooks@1.7.0
> ```
> 
> i checked my `node_modules` and confirmed eslint@7.11.0 is there.

Good catch @resurreccionl, its looks like Create-React-App wants a different version than what is currently being specified. Forgot to run npm start in client to check if it still runs. Go to `package.json` in client and change `eslint` version to `"^6.6.0"`. Then `npm install` again to reinstall dependencies. Try running it again - it should work. 

When you run `npm run lint` you should see `eslint . --ext .tsx` in the terminal. This means the linter is running. If no errors pop up, it just means the code is formatted correctly.

**Comment by resurl** [comment]
> Good catch @resurreccionl, its looks like Create-React-App wants a different version than what is currently being specified. Forgot to run npm start in client to check if it still runs. Go to `package.json` in client and change `eslint` version to `"^6.6.0"`. Then `npm install` again to reinstall dependencies. Try running it again - it should work.
> 
> When you run `npm run lint` you should see `eslint . --ext .tsx` in the terminal. This means the linter is running. If no errors pop up, it just means the code is formatted correctly.

@johnagl  thank you, that worked! everything seems to be fine now.

**Review by resurl — APPROVED** [review]

**Comment by jacksonyuanjx** [comment]
Thanks @johnagl and @resurreccionl for the comments & suggestions! The last commit downgrades eslint in the `/client` dir to ^6.6.0 as suggested so it should fix the `npm start` issue.

**Pull request merged**
