### PR TITLE
Fix: deselecting labs/tutorials

### LINKED ISSUE #120: Fix lab section layout, selection of labs
Fix lab sections screen:
1) Layout should closely resemble wireframes
2) Selected lab section should appear on schedule and the tab should appear selected/highlighted. Right now the lab section gets added but the tab isn't highlighted
3) Add feature to deselect as mentioned by @yehee in #123

Question for designers:
1) Should we even display lab sections that overlap with current courses? If yes, how should we show that they overlap? 

Wireframes:
labSection

Actual:
labSection2

### LINKED ISSUE #123: Deselecting of labs/tutorials not working

### PR DESCRIPTION
**Pull request by yehee**
## Changes
- Allow user to deselect labs/tutorials that they have previously selected
- `selectedSchedule` stored on redux is now a `CourseSection[]`

## Motivation and Context

- To improve overall user experience

## How Has This Been Tested?

- Tested locally

## Related Issues
- Closes issue #123 

## Note
- Should only be able to select one of the labs/tutorials per course; noted in #125

## Checklist
- [x] linter
- [x] package dependencies

### CODE REVIEW

**Review by johnagl — COMMENTED** [review]
This is great @yehee! We can select and deselect. It worked fine when I tested with only 1 course. However when I selected 2 courses, I ran into a bug - these were the steps I took: 

1) Select term 1
2) Add CPSC 320, CPSC 310
3) Skip restrictions
4) On the lectures tab, stay with the default schedule 1, and go to the lab screen

You'll notice below that no lectures show up on the schedule and the schedule grid looks squished.
aliceError2

After a bit more digging, it may be related to the redux state. Notice how selectedSchedule array is empty! 
aliceError3

If I select schedule 2, it works fine. This bug seems to only happen if I stick with the default schedule 1. Lets try to fix the no courses appearing in labs screen issue first - the squished grid one can be a separate PR.

**Comment by yehee** [comment]
@johnagl Thanks for investigating this issue! It definitely slipped through as I always go with the second one :( Seems like it's to do with how we don't have any default set anymore (it used to be 0 as in you stick with the first option), I almost think this is actually what we would want to see happen considering that we're going to have `lock` button for users to clearly state their selection. What do you think? I could quickly create that button to complete the entire workflow if necessary!

**Comment by johnagl** [comment]
> @johnagl Thanks for investigating this issue! It definitely slipped through as I always go with the second one :( Seems like it's to do with how we don't have any default set anymore (it used to be 0 as in you stick with the first option), I almost think this is actually what we would want to see happen considering that we're going to have `lock` button for users to clearly state their selection. What do you think? I could quickly create that button to complete the entire workflow if necessary!

@yehee In the meeting we discussed a "lock" button but decided that it was intuitive enough that we don't need one. By intuitive, I mean that it seems fairly obvious that by selecting next, we're implicitly locking the current schedule.

Maybe I'm not completely understanding what you mean by a lock button?

**Comment by yehee** [comment]
@johnagl Here's what I think about how users would interact with this feature: users would go through the list, stops at the second option thinking it looks good. The user clicks on the `lock/select` button, but he's curious to see what other options are there so he would keep going through the list without having to remember that the best option was the second one?

Not sure if this at all makes sense 😞

**Comment by johnagl** [comment]
> @johnagl Here's what I think about how users would interact with this feature: users would go through the list, stops at the second option thinking it looks good. The user clicks on the `lock/select` button, but he's curious to see what other options are there so he would keep going through the list without having to remember that the best option was the second one?
> 
> Not sure if this at all makes sense 😞

OH. Okay now it makes sense. I wasn't thinking about the user wanting to save, and go to the next schedules just to see what the other options are. Would this require more than 1 schedule grid on the screen? I feel like being forced to select/save an entire schedule makes it harder to customize the schedule since you might want 1 course in a given schedule, but then another course in a second schedule... 

Note that I believe we are also going to add a feature to lock specific lectures that the user wants, so if they see one they like (eg. CPSC 310 201), they can lock it right away. When they select next, the lecture they locked will still be on the schedule as mentioned in #121.

**Comment by johnagl** [comment]
> @johnagl Here's what I think about how users would interact with this feature: users would go through the list, stops at the second option thinking it looks good. The user clicks on the `lock/select` button, but he's curious to see what other options are there so he would keep going through the list without having to remember that the best option was the second one?
> 
> Not sure if this at all makes sense 😞

Also, am i correct in understanding that you want a lock button to save the ENTIRE schedule? Not just one course?

**Comment by yehee** [comment]
> Note that I believe we are also going to add a feature to lock specific lectures that the user wants, so if they see one they like (eg. CPSC 310 201), they can lock it right away. When they select next, the lecture they locked will still be on the schedule as mentioned in #121.

Oh so the user should also be able to select a particular section to always be part of their timetable?

> Also, am i correct in understanding that you want a lock button to save the ENTIRE schedule? Not just one course?

I thought that was the intention behind it, but it seems like that is not the case here! I'm not quite sure how that would be implemented, has there been any progress on that feature?

**Comment by johnagl** [comment]
> > Note that I believe we are also going to add a feature to lock specific lectures that the user wants, so if they see one they like (eg. CPSC 310 201), they can lock it right away. When they select next, the lecture they locked will still be on the schedule as mentioned in #121.
> 
> Oh so the user should also be able to select a particular section to always be part of their timetable?
> 
> > Also, am i correct in understanding that you want a lock button to save the ENTIRE schedule? Not just one course?
> 
> I thought that was the intention behind it, but it seems like that is not the case here! I'm not quite sure how that would be implemented, has there been any progress on that feature?

I believe @danielchen-pyc is looking into it for this week. I'm probably going to have to look at the feasibility of locking 1 course on the schedule, it should be doable by adding an onClick/onSelect function on the sections. I made some additions to #121 , but basically if a user locks in a specific section, there wil have to be recalculations of the valid schedules. If I select CPSC 310 203, then no other 310 sections should show up AND sections that overlap shouldn't show up either.

What do you think? @yehee. This is what we've set out to do, but it could still change.

**Comment by johnagl** [comment]
> > > Note that I believe we are also going to add a feature to lock specific lectures that the user wants, so if they see one they like (eg. CPSC 310 201), they can lock it right away. When they select next, the lecture they locked will still be on the schedule as mentioned in #121.
> > 
> > 
> > Oh so the user should also be able to select a particular section to always be part of their timetable?
> > > Also, am i correct in understanding that you want a lock button to save the ENTIRE schedule? Not just one course?
> > 
> > 
> > I thought that was the intention behind it, but it seems like that is not the case here! I'm not quite sure how that would be implemented, has there been any progress on that feature?
> 
> I believe @danielchen-pyc is looking into it for this week. I'm probably going to have to look at the feasibility of locking 1 course on the schedule, it should be doable by adding an onClick/onSelect function on the sections. I made some additions to #121 , but basically if a user locks in a specific section, there wil have to be recalculations of the valid schedules. If I select CPSC 310 203, then no other 310 sections should show up AND sections that overlap shouldn't show up either.
> 
> What do you think? @yehee. This is what we've set out to do, but it could still change.

One of the advantages of doing it this way is that you can eliminate/filter out invalid schedules once you've selected more sections. This is probably more efficient than having to look at 100 different options. If we select 2 courses right away, it might filter out 50 other schedules that are invalid due to our selections.

**Review by johnagl — APPROVED** [review]
@yehee I think this should be good once the default schedule is being set. Approving for now in the meantime :).

**Pull request merged**
