### PR TITLE
Set up router

### PR DESCRIPTION
**Pull request by aldy97**
# Changes
- Set up the router for the purpose of switching pages
- Added two mock pages and home as default page
- Imported styled-components for scoped and modular styles

## Motivation and Context
- This allows users to switch slides by single click in the future, even though it might just be a single page at current stage.

## How Has This Been Tested?
- The web app can be directed to different pages by clicking the link in component SlidesController

## Related Issues
- Potentially it might conflict with the home boilerplate being worked on by Gagan.

### CODE REVIEW

**Comment by johnagl** [comment]
Looks good! But there are a bunch of linting errors. You can run `npm run lint` to see them. Or rebase / merge the latest master code because @resurreccionl added code that should automatically underline lint errors in VSCode.

**Comment by aldy97** [comment]
@johnagl Hi, I fixed linter errors of quotation mark by adding prettier config into package.json.

**Review by johnagl — DISMISSED** [review]

**Comment by jacksonyuanjx** [comment]
> @johnagl Hi, I fixed linter errors of quotation mark by adding prettier config into package.json.

hey @aldy97 , I thought the existing linter should enforce double quotations?

**Comment by johnagl** [comment]
> > @johnagl Hi, I fixed linter errors of quotation mark by adding prettier config into package.json.
> 
> hey @aldy97 , I thought the existing linter should enforce double quotations?

I dont think it does, we don't have prettier yet, but this PR shouldn't include prettier - that should be separate

**Comment by jacksonyuanjx** [comment]
> > > @johnagl Hi, I fixed linter errors of quotation mark by adding prettier config into package.json.
> > 
> > 
> > hey @aldy97 , I thought the existing linter should enforce double quotations?
> 
> I dont think it does, we don't have prettier yet, but this PR shouldn't include prettier - that should be separate

Hmm, I tried changing to single quotes and ran the linter and got this?

image

**Comment by aldy97** [comment]
@johnagl okay, I am gonna remove the prettier config from the package.json then

**Comment by aldy97** [comment]
> > > > @johnagl Hi, I fixed linter errors of quotation mark by adding prettier config into package.json.
> > > 
> > > 
> > > hey @aldy97 , I thought the existing linter should enforce double quotations?
> > 
> > 
> > I dont think it does, we don't have prettier yet, but this PR shouldn't include prettier - that should be separate
> 
> Hmm, I tried changing to single quotes and ran the linter and got this?
> 
> image

Yeah I saw the same thing, but it is an expected behavior right?

**Review by johnagl — APPROVED** [review]

**Pull request merged**
