### PR TITLE
Generate share link

### PR DESCRIPTION
**Pull request by johnagl**
# Changes
- Implementation of shareable link (still have to do some styling later)

## How Has This Been Tested?
Locally

## Screenshots (if appropriate):

Updated so that link isn't this long anymore - we store it in the database and use the id.
shareLinkLong

After pasting link into browser
gridShareLink

# Related Issues
- #146 

# Checklist

### CODE REVIEW

**Comment by johnagl** [comment]
Does anyone have suggestions for decreasing the link length? I'm essentially putting all the necessary course info in the link so I don't have to query the database.

**Comment by jacksonyuanjx** [comment]
> Does anyone have suggestions for decreasing the link length? I'm essentially putting all the necessary course info in the link so I don't have to query the database.

I have a few questions/thoughts.
* Why don't we want to query the database when users use the sharable link? I think it'll be difficult to avoid querying the database if we want a short sharable link.
* We could try an encoding method to make the data look better and possibly shorter so it's not like raw JSON in the URL
* What was the reasoning for not using a DB in general to map like a unique ID to a worklist? Wouldn't that allow us to produce very short and clean URLs? Or are we just concerned about the DB's capacity? If it's just a capacity concern, I think we have over 3.5k free rows that we can use before crossing the limit and I think it'll take a decent number of users to cross that limit.

**Comment by resurl** [comment]
to add on to what jackson's saying, i like the idea of making unique ids aesthetically but if database storage is a concern, there's already an unused course api controller that lets you select sections given a course code + section number (`getSectionWithTerm` i think it was called?), so we could have links like `coursecode.ca/CPSC_310_101%20PSYC_200_102%20blahblah` instead.

**Comment by yehee** [comment]
I second @jacksonyuanjx about querying the database, seems like it wouldn't hurt us much!

**Comment by johnagl** [comment]
@jacksonyuanjx @resurreccionl @yehee I guess I was thinking more of maintainability of the DB (the db getting full and us having to clear the table). Also because we don't have logins or anything, it's really easy for a user to click save multiple times and save 10 schedules in 1 sitting. But I guess we shouldn't worry about problems we dont have yet anyways... so I guess I'll store the worklist into the DB for now.

**Comment by johnagl** [comment]
Just noticed that invalid id just gives an empty schedule, will probably have to fix that later with some sort of disclaimer.

**Comment by jacksonyuanjx** [comment]
Is it just me that gets this CORS issue?

image

**Comment by johnagl** [comment]
> Is it just me that gets this CORS issue?
> 
> image

Stupid CORS lol. I'll take a look soon - it's probably just adding some line in the index server file. But hard for me to test since I'm not getting it atm.

**Comment by johnagl** [comment]
@jacksonyuanjx pull and try again.... let me know if it works.

**Comment by jacksonyuanjx** [comment]
@johnagl It still doesn't work haha but I think it's just a browser issue, probably on my end. If it works on yours, we're probably good to go. Might be better if someone else tested it as well but from the demo you showed today, everything seems good.

**Comment by johnagl** [comment]
> @johnagl It still doesn't work haha but I think it's just a browser issue, probably on my end. If it works on yours, we're probably good to go. Might be better if someone else tested it as well but from the demo you showed today, everything seems good.

K. This is bugging me now, I tried one LAST thing - if this doesn't work we can just try pushing to see if it works in production once someone else tests it.

**Comment by jacksonyuanjx** [comment]
@johnagl So I think I fixed it by using the [cors package](https://www.npmjs.com/package/cors) in the `server/src/index.ts` file by first importing it, then adding this line of code: `app.use(cors());`. 

I also gave the shared link feature a quick test and it seems like if the user just spams the "generate" button for the same schedule, they're able to keep creating new entries into our DB. Should we have a small feature to lock the "generate" button until the user refreshes or makes a change to the schedule?

**Comment by johnagl** [comment]
> @johnagl So I think I fixed it by using the [cors package](https://www.npmjs.com/package/cors) in the `server/src/index.ts` file by first importing it, then adding this line of code: `app.use(cors());`.
> 
> I also gave the shared link feature a quick test and it seems like if the user just spams the "generate" button for the same schedule, they're able to keep creating new entries into our DB. Should we have a small feature to lock the "generate" button until the user refreshes or makes a change to the schedule?

Ah. okay, yeah that's the other way, I was doing it the manual way without that package...

**Comment by johnagl** [comment]
> @johnagl So I think I fixed it by using the [cors package](https://www.npmjs.com/package/cors) in the `server/src/index.ts` file by first importing it, then adding this line of code: `app.use(cors());`.
> 
> I also gave the shared link feature a quick test and it seems like if the user just spams the "generate" button for the same schedule, they're able to keep creating new entries into our DB. Should we have a small feature to lock the "generate" button until the user refreshes or makes a change to the schedule?

Yeah I was thinking about this - I added a ticket for rate limiting in issues... there are probably other ways to prevent users from spamming the DB.

**Comment by johnagl** [comment]
@jacksonyuanjx you can push the cors change up.

**Review by jacksonyuanjx — APPROVED** [review]
Everything else LGTM. I guess we can leave the fixes for the empty schedule page, rate-limiting, etc, for future issues.

**Pull request merged**
